name: Windows_host

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  # =============================================================================================================
  build_win:
    name: Build Windows
    runs-on: windows-2022
    defaults:
      run:
        working-directory: build/gcc
    # ===============================================================================================
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      # ===============================================================================================
      - name: Build
        run: |
          make all