name: Static_analysis

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
# =============================================================================================================
  build_cppcheck:
    name: Cpp Check analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      # ===============================================================================================
      - name: Install additional packages
        run: |
          sudo apt-get install check
      # ===============================================================================================
      - name: Build
        run: |
          cd build/gcc
          make all
          make check
      # ===============================================================================================
      - name: Run cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          other_options: --xml
      # ===============================================================================================
      - name: Prepare cppcheck results
        run: |
          find . -name 'cppcheck_report.*'
          REPORT_PATH=$(find . -name 'cppcheck_report.*' -exec dirname {} \;)
          cd REPORT_PATH
          mv cppcheck_report.txt cppcheck_report.xml
      # ===============================================================================================
      - name: Archive cppcheck results
        uses: actions/upload-artifact@v1
        with:
          name: cppcheck-report
          path: $REPORT_PATH/cppcheck_report.xml