name: Memory_analysis

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
# =============================================================================================================
  build_cppcheck:
    name: Valgrind analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      # ===============================================================================================
      - name: Install additional packages
        run: |
          sudo apt-get -y --allow-remove-essential install valgrind check
      # ===============================================================================================
      - name: Build
        run: |
          cd build/gcc
          make all
          make check
          make examples
      # ===============================================================================================
      # Search for executable files (tests) and run valgrind on each of them
      - name: Run Valgrind
        run: |
          cd bin/tests
          mv test_emptyType ../
          find . -type f -executable -print0 | while IFS= read -r -d '' executable; do
              echo "Checking: $executable"
              valgrind --leak-check=yes --leak-check=full --show-leak-kinds=all "$executable 2> error.log 1> /dev/null"
          done
          mv ../test_emptyType .

          cd ../examples/simpleDecoding
          valgrind --leak-check=yes exipd ../../tests/external/valgrind-checks/test-set/SchemaLess-WrongBody.exi 2> error.log 1> /dev/null 
          valgrind --leak-check=yes exipd ../../tests/external/valgrind-checks/test-set/SchemaLess-TotallyWrong.exi 2>> error.log 1> /dev/null
          valgrind --leak-check=yes exipd -schema ../../tests/external/valgrind-checks/test-set/Schema.exi ../../tests/external/valgrind-checks/test-set/Schema-WrongBody.exi 2>> error.log 1> /dev/null
          valgrind --leak-check=yes exipd -schema ../../tests/external/valgrind-checks/test-set/Schema.exi ../../tests/external/valgrind-checks/test-set/Schema-TotallyWrong.exi 2>> error.log 1> /dev/null

          grep "ERROR SUMMARY" < error.log