name: Static_analysis

on: [push, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
# =============================================================================================================
  build_cppcheck:
    name: Build Cpp Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      # ===============================================================================================
      - name: Install additional packages
        run: |
          sudo apt-get -y --allow-remove-essential install valgrind check
      # ===============================================================================================
      - name: Build
        run: |
          cd build/gcc
          make all
          make check
      # ===============================================================================================
      # Search for executable files (tests) and run valgrind on each of them
      - name: Run Valgrind
        run: |
          find /bin/tests -type f -executable -print0 | while IFS= read -r -d '' executable; do
              echo "Checking: $executable"
              valgrind --leak-check=yes --leak-check=full --show-leak-kinds=all "$executable"
          done